### ISSUE TITLE
Juju 2.2-rc1 breaks libjuju 0.4.0

### ISSUE THREAD

**Issue by simonklb** [juju/python-libjuju#134]
Having issues with a Docker image I built for a charm that uses libjuju 0.4.0.

```
% python3.5 -m venv .libjujutest
% . .libjujutest/bin/activate
% pip install juju==0.4.0
% python
>>> from juju import loop, model
>>> m = model.Model()
>>> loop.run(m.connect_current())
Could not find a set of facades for 2.2-rc1. Using the latest facade set instead
Could not find a set of facades for 2.2-rc1. Using the latest facade set instead
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/simon/.libjujutest/lib/python3.5/site-packages/juju/loop.py", line 31, in run
    raise task.exception()
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/simon/.libjujutest/lib/python3.5/site-packages/juju/model.py", line 410, in connect_current
    await self._after_connect()
  File "/home/simon/.libjujutest/lib/python3.5/site-packages/juju/model.py", line 428, in _after_connect
    await self.get_info()
  File "/home/simon/.libjujutest/lib/python3.5/site-packages/juju/model.py", line 570, in get_info
    self.info = await facade.ModelInfo()
  File "/home/simon/.libjujutest/lib/python3.5/site-packages/juju/client/facade.py", line 411, in wrapper
    result = cls.from_json(reply['response'])
  File "/home/simon/.libjujutest/lib/python3.5/site-packages/juju/client/facade.py", line 529, in from_json
    return cls(**d)
TypeError: __init__() got an unexpected keyword argument 'agent-version'
>>>
```

```
% juju status
Model    Controller     Cloud/Region   Version  SLA
default  aws-eu-west-1  aws/eu-west-1  2.2-rc1  unsupported
```

No issues with the latest release of libjuju. Just curious what the best way of handling charms that uses libjuju. Is there any promises in core Juju that it will be backwards compatible for X number of versions or something like that?

**Comment by johnsca** [comment]
As you mentioned, the current version of libjuju, [0.4.3](https://pypi.python.org/pypi/juju/), has [a fix](https://pythonhosted.org/juju/#id1) for this issue.  It does also include a fix so that new, backwards compatible field additions don't cause such a break in the future.

The promise that Juju makes is that the facade version will be updated if any non-backwards-compatible change is made, such as a new optional field being added, or new data being returned by the API.  I believe it is also the case that a given major version release of Juju promises to support all older facade versions up to the start of that major version, meaning that a client supporting any version of 2.x should be able to talk to any controller of equal or higher revision, and may be able to talk to a controller of lower revision as long as it is willing to use the older facade versions with appropriate reduction in functionality.

With libjuju, we are targeting the former but not the latter.  Unfortunately, before 0.4.3, libjuju took issue with unexpected new data coming in from the API, but that has now been resolved.  We're also working to get libjuju tests added as part of the review process for Juju core to ensure that libjuju is updated in a timely fashion in response to changes to the Juju API.
