### ISSUE TITLE
is_bootstrapped fails if juju is not installed

### ISSUE THREAD

**Issue by johnsca** [juju/python-libjuju#246]
```
tests/unit/test_controller.py:9: in <module>
    from .. import base
tests/base.py:22: in <module>
    not is_bootstrapped(),
tests/base.py:15: in is_bootstrapped
    result = subprocess.run(['juju', 'switch'], stdout=subprocess.PIPE)
/usr/lib/python3.6/subprocess.py:403: in run
    with Popen(*popenargs, **kwargs) as process:
/usr/lib/python3.6/subprocess.py:709: in __init__
    restore_signals, start_new_session)
/usr/lib/python3.6/subprocess.py:1344: in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
E   FileNotFoundError: [Errno 2] No such file or directory: 'juju': 'juju'
```

It should just return `False`.

Also, should investigate why at least two supposed unit tests depend on a bootstrapped controller.

**Comment by gnuoy** [comment]
I maybe missing something but I don't think there are unit tests that are dependant on a bootstrapped controller. I think the problem is that the ```tests.base.bootstrapped``` decorator causes ```is_bootstrapped``` to
be evaluated at import time eg a test merely has to import the module for is_bootsrapped to be run regardless of whether it uses it.
