### ISSUE TITLE
Syncronous API

### ISSUE THREAD

**Issue by stub42** [juju/python-libjuju#358]
Most Python code cannot use libjuju directly, as it provides an asynchronous API. To avoid most Python code needing to write their own wrappers, it would be great if synchronous wrappers could be generated in addition to the asynchronous ones.

**Comment by SimonRichardson** [comment]
Unfortunately the underlying connection layer that enables the communication between the pylibjuju library and the juju API server requires websockets and that uses an asynchronous API. This then flows throughout the code base because of this. The effort required to change this would be significant. Unless I'm missing something?

**Comment by johnsca** [comment]
It's fairly easy to call async code from synchronous code by doing `loop.run_until_complete(async_func)`.  In theory, it should be possible to create a shim which takes an object to proxy to and automatically wraps any async methods with this, but doing that implicitly and hiding the fact that it's async feels a bit dirty for what amounts to some syntactic sugar.  Maybe it would just be better to call out `loop.run_until_complete` better in the docs?  Alternatively, we could provide the shim in utils or something and document that if you want the sugar, you can wrap the objects explicitly yourself?

**Comment by stub42** [comment]
Python 3.7 provides asyncio.run(). zaza has a zaza.run() helper that works with 3.6.

I'm still interested in exposing a syncronous API though, possibly by generating a separate module or package in the same way the async one is generated (I haven't looked at this and do not know if it is practical). Even with the helpers, things become more difficult with async APIs (eg. until async test case support lands in Python 3.8+, coroutines can be left dangling after the test completes, breaking test isolation, unless all the scaffolding is added to create new loops per test case and maybe leak detection).

**Comment by juanmanuel-tirado** [comment]
We have ongoing discussions on how to proceed with this issue. Most of the python-libjuju adopters do not use any of the asynchronous functions exposed by this library in an concurrent manner. I will close this issue because there has not been any activity here for three years. However, the discussion remains opens.
