### ISSUE TITLE
Remove or double-down on Paramiko dependency for SSH

### ISSUE THREAD

**Issue by johnsca** [juju/python-libjuju#394]
The [manual provisioning code](https://github.com/juju/python-libjuju/blob/master/juju/provisioner.py) uses the Paramiko library to invoke commands on the new machines via SSH, but #393 shows that it may be simpler to simply use async subprocesses to the command-line SSH client.  I think the original rationale was to enable support on systems that didn't have an ssh command-line client.  If that's still a concern, then we should convert the model code to use Paramiko instead, but if it's not, it would be great to be able to remove that dependency.

**Comment by johnsca** [comment]
@davigar15 I believe you can shed some light on whether we need to be concerned about the potential lack of an ssh CLI client?

**Comment by AdamIsrael** [comment]
@johnsca The only reason for Paramiko, that I can recall, was because that's what I was familiar with at the time. I remember that we talked briefly about using `asyncssh` at one point.

I think it's safe to assume -- or require -- the machine running the provisioner to have an ssh client installed, though.

**Comment by juanmanuel-tirado** [comment]
Close. Follow comments on #399
