### ISSUE TITLE
Application status not getting properly updated

### ISSUE THREAD

**Issue by davigar15** [juju/python-libjuju#441]
Juju controller version: 2.8.2
Libjuju version: 2.8.3 (In 2.8.2 happens too)

Description of the issue: we get from the app.status a "waiting" when we should get blocked

Python script to reproduce the bug:
https://pastebin.canonical.com/p/gZKZmBn62b/

Output: https://pastebin.canonical.com/p/v4bk2TB58D/ 
^ We expect to retrieve a “blocked” string instead of “waiting”

**Comment by SimonRichardson** [comment]
Unfortunately, the workaround until I can fully test all scenarios (see pastebin). The real problem is that I'm unsure how to handle application status for older jujus. Is it safe to always read the unit status and then derive that for even older jujus or do we have to do some facade checking? The problem with this is that I believe the changes didn't actually bump a facade, so it will be very difficult to identify when the change happened.

https://pastebin.canonical.com/p/kJ7jKmSRP8/

**Comment by davigar15** [comment]
It's happening with this charm: cs:~davigar15/simple-native-0
