### ISSUE TITLE
Add hostname attribute to machine object

### ISSUE THREAD

**Issue by xavpaice** [juju/python-libjuju#474]
With https://github.com/juju/juju/pull/12754 being merged, and in 2.8.10, I'd like to access this new information via libjuju.  It would be great if we could have this available via machine.hostname, same as we can have machine.dns_name now.

**Comment by SimonRichardson** [comment]
@achilleasa ping, how feasible is it to get that information. I'm assuming that it would require a separate call as that information isn't coming over via the AllWatcher.

**Comment by achilleasa** [comment]
@SimonRichardson Not sure how this works in python-land. Does the AllWatcher simply marshal the entity and send it through? If that's the case, it should show up as a 'hostname' attribute on the machine model (we would just need a helper to check if it's there because this will only work on 2.8.10+; not yet ported to 2.9). Otherwise, we need to find where the `dns_name` attribute gets serialized and add `hostname` there as well.

**Comment by SimonRichardson** [comment]
@achilleasa This is the underlying type that is sent via the `AllWatcher`. https://github.com/juju/juju/blob/develop/core/multiwatcher/types.go#L75-L102

**Comment by achilleasa** [comment]
Hmmm... So I presume we get the Machine via another API call? https://github.com/juju/python-libjuju/blob/master/juju/machine.py#L178 (this one has dns_name as an attribute; do we populate this from FullStatus reponses?)

**Comment by SimonRichardson** [comment]
It uses the following https://github.com/juju/python-libjuju/blob/master/juju/machine.py#L311 as a best guess.
