### ISSUE TITLE
`block_until` does not take async conditions

### ISSUE THREAD

**Issue by sed-i** [juju/python-libjuju#609]
For an integration test I wrote a helper function that needs to block until some async condition is met:

```python
async def block_until_leader_elected(ops_test: OpsTest, app_name: str):
    async def is_leader_elected():
        units = ops_test.model.applications[app_name].units
        return any([await units[i].is_leader_from_status() for i in range(len(units))])

    await ops_test.model.block_until(is_leader_elected)
```

But `block_until` does not take async conditions:

https://github.com/juju/python-libjuju/blob/96a15ab1492d296a6608f75e68df97fad13d3877/juju/model.py#L880-L881

```
tests/integration/test_rescale_charm.py::test_deploy_multiple_units
  /home/ubuntu/cos/alertmanager-k8s-operator/.tox/integration/lib/python3.9/site-packages/juju/model.py:877: RuntimeWarning: coroutine 'block_until_leader_elected.<locals>.is_leader_elected' was never awaited
    return _disconnected() or all(c() for c in conditions)
```

**Comment by cderici** [comment]
Yes, model's `block_until` (just like the underlying `block_until` from utils) takes regular python functions. Blocking with coroutine predicates is non-trivial, since (a) the `asyncio` itself doesn't seem to provide a good abstraction to do that, (b) it gets complicated quickly if exception handling is involved. 

I'll try to come up with a custom utility for this one, so you can call it like:

```python
async def block_until_leader_elected(ops_test: OpsTest, app_name: str):
    async def is_leader_elected():
        units = ops_test.model.applications[app_name].units
        return any([await units[i].is_leader_from_status() for i in range(len(units))])

    await utils.block_until_with_coroutines(is_leader_elected())
```
