### ISSUE TITLE
[Bug]: controller.list_models stuck when use jasyncio.run

### ISSUE THREAD

**Issue by jneo8** [juju/python-libjuju#763]
### Description

Found from [bug/1989302](https://bugs.launchpad.net/juju-backup-all/+bug/1989302)

`jasyncio.run` can not work together with `controller.list_models`

Work prefect with async function.

```python
import asyncio
from juju.controller import Controller
import logging


async def main():
    controller = Controller()
    await controller.connect("local-lxd")
    logging.debug(controller.is_connected())
    logging.debug(await controller.list_models())

if __name__ == "__main__":
    asyncio.run(main())
```

But with synchroously, it will stuck forever at line `run_async(controller.list_models())`

```python
from juju.controller import Controller
from juju.jasyncio import run as run_async
import logging


def main():
    controller = Controller()
    run_async(controller.connect("local-lxd"))
    logging.debug(dir(controller))
    logging.debug(controller.is_connected())
    logging.debug(run_async(controller.list_models()))


if __name__ == "__main__":
    main()
```

### Urgency

Blocker for our release

### Python-libjuju version

3.0.3
### python version

3.10.4

### Juju version

2.9.36, 2.9.35

### Reproduce / Test

```python
from juju.controller import Controller
from juju.jasyncio import run as run_async
import logging


def main():
    controller = Controller()
    run_async(controller.connect("local-lxd"))
    logging.debug(dir(controller))
    logging.debug(controller.is_connected())
    logging.debug(run_async(controller.list_models()))


if __name__ == "__main__":
    main()
```

**Comment by juanmanuel-tirado** [comment]
You're right in your case, `list_models` is blocking. It is not clear to me if that is a problem of the function itself or something different. Interestingly, you can manage to move forward by disconnecting the controller.

```python
from juju import jasyncio
from juju.controller import Controller

async def main():
    controller = Controller()
    await controller.connect("c300")
    print(controller.is_connected())
    print(await controller.list_models())
    await controller.disconnect()

if __name__ == "__main__":
    jasyncio.run(main())
```

The asynchronous model of python-libjuju is going to be revisited. Please, proceed with the most convenient solution for you at this moment.

**Comment by jneo8** [comment]
If I understand right

It's because `jasyncio.run` create a new event loop every time we call it.

If we create a controller connect in the first event loop, it will create a new websocket which connect to first thread's `asyncio.IdQueue`.

But later we call another `jasyncio.run` function, because the connection was created before, the result was send to first thread's `asyncio.IdQueue`. 
And this new thread will try to receive result from the `IdQueue` created this time.
 
 So it will pending forever.

**Comment by ajkavanagh** [comment]
@jneo8 It's tricky using libjuju from sync code, because of the way it creates coroutines that "expect" to keep running.  We sort of solved the problem with zaza by running the linbjuju async co-routines in a background thread and then passing co-routines into the background thread when they needed to call into libjuju.  In this way libjuju continues to run the coroutines necessary to keep up with status changes, etc, and zaza can continue to be non-async, blocking, code.  Not sure if it's great, but is does work!

Relevant code is here: https://github.com/openstack-charmers/zaza/blob/master/zaza/__init__.py

There is a handy `run()` function to run an async function in libjuju's thread: https://github.com/openstack-charmers/zaza/blob/a7faa9a6ada5d3838bdc6edddc97b3e322234f57/zaza/__init__.py#L234

**Comment by juanmanuel-tirado** [comment]
As @ajkavanagh says, the python-libjuju async model is far away from being easy-to-understand. Really interesting code. Thanks for sharing.
Please, notice that `jasyncio` is a wrapper we had to add in order to keep compatibility with `asyncio` and older python versions. We plan to deprecate it soon.

**Comment by jneo8** [comment]
@ajkavanagh  Thanks for your interesting sharing, it's a nice solution. I will discuss with our team next week, there is a working solution in zaza for us to learn.

@juanmanuel-tirado One question. What is the policy after deprecated `jasyncio`? There is a new alternative? There will be no more non-sync way to run? What about those legacy code are still non-async? Thanks.

**Comment by cderici** [comment]
> One question. What is the policy after deprecated `jasyncio`? There will be an alternative? There will be no more non-sync way to run? What about those legacy code are still non-async? Thanks.

The whole point of `jasyncio` is to be a thin wrapper around `asyncio` to make sure everything's consistent across the different Python versions. (for instance the `create_task` function was added in Python `3.7`, so for earlier versions the `jasyncio` introduces `create_task` as a function around the `ensure_future` which did exist before `3.7`, so everyone has access to `create_task`.)

@jneo8  The deprecation that @juanmanuel-tirado is talking about is moving things back to `asyncio`, instead of going through a wrapper like `jasyncio`. So from the user's perspective essentially things are gonna stay the same (modulo some small changes here and there).

**Comment by jneo8** [comment]
@cderici  Thanks for your clear answer.
