### ISSUE TITLE
[Bug]: ops_test.model.wait_for_idle does not respect argument

### ISSUE THREAD

**Issue by beliaev-maksim** [juju/python-libjuju#837]
### Description

wait_for_units has following definition:
```
param wait_for_units (int): The least number of units to be expected before
            going into the idle state.
            The default is 1 unit.
```

in our scenario juju for some reason scaled up the app, so, we have 2/1. But I do not care about the second unit, since we can work only with leader

now all the tests hang, since second unit is in waiting status and waits for the leadership.

if I say `wait_for_units=1`, then logically it should say we are good even if only 1 unit is in idle/active

![image](https://user-images.githubusercontent.com/51964909/233265422-cebb5354-1081-4794-b182-8fd167551aaf.png)

### Urgency

Annoying bug in our test suite

### Python-libjuju version

2.9.42.1

### Juju version

2.9.42

### Reproduce / Test

```python
    await ops_test.model.wait_for_idle(
        apps=apps,
        status="active",
        raise_on_blocked=False,
        raise_on_error=False,
        timeout=from_minutes(minutes=100),
    )
```

**Comment by juanmanuel-tirado** [comment]
Ignoring that juju should not scale up your app, this looks like a bug.

Looking here: https://github.com/juju/python-libjuju/blob/cfc12d9fa9997a1a8974aa62a3182053ef169343/juju/model.py#L2498
The comparison makes sense. 

Do you have any easy-to-reproduce chunk of code. I'm a bit suspicious about these two lines: https://github.com/juju/python-libjuju/blob/cfc12d9fa9997a1a8974aa62a3182053ef169343/juju/model.py#L2515

**Comment by beliaev-maksim** [comment]
@juanmanuel-tirado 
but 
`elif len(app.units) < wait_for_units:` will not be triggered, right?
since I have then `2 units < 1` which is False

or?

**Comment by juanmanuel-tirado** [comment]
You're right I was reading the comparison in the other direction. 

I'm a bit surprised/confused. This means that this piece of code has never worked as expected...

**Comment by beliaev-maksim** [comment]
@juanmanuel-tirado 
that is exactly my point :D

**Comment by cderici** [comment]
@beliaev-maksim So there's a couple of different points here:

1) if you have 2 units, and you just call `wait_for_idle(wait_for_units=1)` then it hangs, that's a bug, and will be corrected no problem.

2) Having said (1), I believe the docstring about the `wait_for_units` is correct. That parameter will make the `wait_for_idle` continue to wait until it sees that many units are in the expected status. It just hangs because I think we never considered the case where someone would run that with more units than `wait_for_units` parameter. I'll put up a PR about that today 👍 

3) About how your application got scaled? I don't know since I don't see how these got deployed. However, I don't believe `wait_for_idle` is what scaled up your application (I haven't looked at the code closely, but wait_for_idle shouldn't have any code in it to "change" the number of units in your app. Unfortunately your reproducer code doesn't make sense at all without any context. So we're gonna need an actual reproducer for that one.

**Comment by beliaev-maksim** [comment]
@cderici oh, I definitely not blame the lib in scaling :) I just say what happened and then my tests got handing although I see all apps are green. It was so painful to see hahaha :D

ok, then waiting for PRs :)

**Comment by beliaev-maksim** [comment]
@cderici 
yes, without bug fix no go

CI just hangs
![image](https://user-images.githubusercontent.com/51964909/233475351-352f3b8a-6898-444d-98a2-28a56000b36a.png)

**Comment by cderici** [comment]
Looking at this closer now, I don't seem to be able to reproduce this on pylibjuju. I think this might be the case where juju hangs in the background. 

@beliaev-maksim is there an easy way for us to run this exactly the way you do? Or is there a way for you to check the `juju status` while this is waiting? It might be hard to do that if this is CI, but if you can run `juju status`, I suspect that you'll see that the units are waiting there. 

So unless you see that the units are active and idle in the `juju status` but the pylibjuju is waiting, this doesn't look like a bug in the `wait_for_idle`.

**Comment by beliaev-maksim** [comment]
@cderici 
no SSH to the machines


I would agree that it is not a bug if I will have both units printed by pylibjuju
however, now I see only one, assuming that the second is up and running

cuz as on the first screenshot, it looks like it reached active

**Comment by cderici** [comment]
@beliaev-maksim Yeah I think I see the problem, so you have 1 unit that's available, and you want the `wait_for_idle` to return because "of all the units of the application I need only 1 of them to be in `active` status", while `wait_for_idle` needs all of them to be in the same status to return. No worries I can fix that 👍

**Comment by beliaev-maksim** [comment]
@cderici 
yes, according to the description I think it should be "at least X" units in status. Not all of them

**Comment by beliaev-maksim** [comment]
for sure an issue, just hit it again on another deployment 

![image](https://user-images.githubusercontent.com/51964909/233752033-d387d22d-4fec-43f3-8458-23f47435591a.png)
