### ISSUE TITLE
`wait_for_idle` returns prematurely when `wait_for_units` is provided 

### ISSUE THREAD

**Issue by sed-i** [juju/python-libjuju#886]
When `wait_for_units` is provided, we exit the loop before checking the `waiting_for_a_particular_status` logic.
https://github.com/juju/python-libjuju/blob/ad62156b3bd18c949cd7f65a6b528cbaf023e121/juju/model.py#L2693-L2696

As a result, when we use something like:
```python
    await ops_test.model.wait_for_idle(
        apps=[grafana_app_name, tester_app_name], status="active", wait_for_units=1, timeout=300
    )
```
the await returns before status is active.

**Comment by cderici** [comment]
We had some iterations for this on the `wait_for_idle` code, but it was on the `2.9` branch, we brought it forward into the master in https://github.com/juju/python-libjuju/pull/870, but evidently we missed something, I'll take another look. 

@sed-i Just to make sure, this is against 3.x controller using libjuju >2.9, right?

**Comment by sed-i** [comment]
Yep,
- juju (3.1/edge) 3.1.4-8fbf7ef
- pylibjuju 3.2.0.0

**Comment by cderici** [comment]
I'm not sure if this is a bug, @sed-i. Problem is that this use case is clashing with the use case in https://github.com/juju/python-libjuju/issues/837. 

In your particular case, you're trying to wait for `grafana_app_name` and `tester_app_name`, what was your reasoning/expectation in passing `wait_for_units=1`? Cause right now it's set to "the least number of units to be expected to be in the status" [here](https://github.com/juju/python-libjuju/blob/ad62156b3bd18c949cd7f65a6b528cbaf023e121/juju/model.py#L2613), which is why it's returning as soon as 1 unit is in the given status. We have another parameter called the [`wait_for_exact_units`](https://github.com/juju/python-libjuju/blob/ad62156b3bd18c949cd7f65a6b528cbaf023e121/juju/model.py#LL2617C16-L2617C37) to wait for exact number of units. Note that it's across multiple applications if you provide multiple apps.

The main problem is that `wait_for_idle` is super overloaded, and it's trying to work across multiple applications at the same time. I need to find a good way for users to express `I want this number of units from applications A and B to be in <status-1> (don't care which app they belong)` and `I don't care about application C's units (they can be in error state) as long as application D has at least 1 unit in <status-2>` at the same time, which is a bit complicated, but doable.

**Comment by sed-i** [comment]
> The main problem is that `wait_for_idle` is super overloaded

Agreed.

> what was your reasoning/expectation in passing wait_for_units=1?

I imagine the original intent was to use `wait_for_units=1` to have a leader, without hard-coding an `idle_period=some_guess`, and before `wait_for_exact_units` was implemented/known.

What seems to be odd is that some args result in an AND condition, but `wait_for_units` results in an OR condition.

I guess an immediate solution could be a doc update :)
