### ISSUE TITLE
Move pyyaml pin to 6.0.1

### ISSUE THREAD

**Issue by dragomirp** [juju/python-libjuju#913]
Some charms started experience packing failures related to pyyaml 6.0, which were addressed by 6.0.1, however when using a dependency management tools like poetry, the tool will respect the maximum pinned version and will respect libjuju's pin to 6.0. The pin seems to be in place for most versions (2.9, 3.1, 3.2).

**Comment by Cynerva** [comment]
Be careful with PyYAML 5.3.1 as it has a known security vulnerability: https://nvd.nist.gov/vuln/detail/CVE-2020-14343

**Comment by ghislainbourgeois** [comment]
This also affects `3.2.0.0`.

**Comment by cderici** [comment]
Closed by #916 & #918

**Comment by dragomirp** [comment]
Hi, @cderici , was the pin moved for 3.1 or just 2.9 and 3.2?

**Comment by cderici** [comment]
> Hi, @cderici , was the pin moved for 3.1 or just 2.9 and 3.2?

Hey @dragomirp, so we don't keep separate tracks for different 3.x versions because Juju API ensures compatibility with each other. I.e., If you're using the latest version of pylibjuju (currently `3.2.0.1`), then it should work with a `3.1` Juju controller as well as `3.2`... The only reason we have a separate 2.9 track is the hard break between the 2.9 and 3.x, and the pin is removed from both tracks 👍
